// <auto-generated />
using System;
using DBConnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DBConnect.Migrations
{
    [DbContext(typeof(SiteDiaryContext))]
    partial class SiteDiaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBConnect.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attachment_type");

                    b.Property<string>("BlobStorageAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("blob_storage_address");

                    b.HasKey("AttachmentId")
                        .HasName("PK__attachme__B74DF4E2BE34FBA8");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("DBConnect.CoinsWb", b =>
                {
                    b.Property<int>("CbsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cbs_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CbsId"));

                    b.Property<string>("WbsCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("wbs_code");

                    b.HasKey("CbsId")
                        .HasName("PK__coins_wb__FE6B9C3F22AA2DB3");

                    b.ToTable("coins_wbs", (string)null);
                });

            modelBuilder.Entity("DBConnect.DiaryEntry", b =>
                {
                    b.Property<int>("DiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("diary_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaryId"));

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activity");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FromDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("from_datetime");

                    b.Property<int>("LogTypeId")
                        .HasColumnType("int")
                        .HasColumnName("log_type_id");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Problems")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("problems");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<DateTime?>("ToDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("to_datetime");

                    b.Property<int?>("WeatherId")
                        .HasColumnType("int")
                        .HasColumnName("weather_id");

                    b.Property<string>("WorksLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("works_location");

                    b.HasKey("DiaryId")
                        .HasName("PK__diary_en__339232C83A2070F2");

                    b.HasIndex("LogTypeId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StaffId");

                    b.HasIndex("WeatherId");

                    b.ToTable("diary_entries", (string)null);
                });

            modelBuilder.Entity("DBConnect.Downtime", b =>
                {
                    b.Property<int>("DowntimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("downtime_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DowntimeLogId"));

                    b.Property<int?>("AttachmentKey")
                        .HasColumnType("int")
                        .HasColumnName("attachment_key");

                    b.Property<int>("CbsKey")
                        .HasColumnType("int")
                        .HasColumnName("cbs_key");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("details");

                    b.Property<TimeOnly?>("DowntimeHours")
                        .HasColumnType("time")
                        .HasColumnName("downtime_hours");

                    b.Property<string>("Impact")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("impact");

                    b.Property<string>("IssuesDelays")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("issues_delays");

                    b.Property<TimeOnly?>("LostManHours")
                        .HasColumnType("time")
                        .HasColumnName("lost_man_hours");

                    b.Property<int?>("NoOfPeopleAffected")
                        .HasColumnType("int")
                        .HasColumnName("no_of_people_affected");

                    b.Property<int>("SiteKey")
                        .HasColumnType("int")
                        .HasColumnName("site_key");

                    b.HasKey("DowntimeLogId")
                        .HasName("PK__downtime__1C118E0182F3D303");

                    b.HasIndex("AttachmentKey");

                    b.ToTable("downtime", (string)null);
                });

            modelBuilder.Entity("DBConnect.LogType", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("LogType1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("log_type");

                    b.HasKey("LogId")
                        .HasName("PK__log_type__9E2397E0F1186BB3");

                    b.ToTable("log_type", (string)null);
                });

            modelBuilder.Entity("DBConnect.Org", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("organisation_name");

                    b.HasKey("OrgId")
                        .HasName("PK__orgs__F6AD8012A55C4456");

                    b.ToTable("orgs", (string)null);
                });

            modelBuilder.Entity("DBConnect.PackageInformation", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("package_name");

                    b.HasKey("PackageId")
                        .HasName("PK__package___63846AE83CD40F73");

                    b.ToTable("package_information", (string)null);
                });

            modelBuilder.Entity("DBConnect.ProjectInformation", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("project_name");

                    b.HasKey("ProjectId")
                        .HasName("PK__project___BC799E1F41B4BE7F");

                    b.ToTable("project_information", (string)null);
                });

            modelBuilder.Entity("DBConnect.SiteCb", b =>
                {
                    b.Property<int>("SiteCbsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("site_cbs_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteCbsId"));

                    b.Property<int>("CbsKey")
                        .HasColumnType("int")
                        .HasColumnName("cbs_key");

                    b.Property<int>("ProjectKey")
                        .HasColumnType("int")
                        .HasColumnName("project_key");

                    b.HasKey("SiteCbsId")
                        .HasName("PK__site_cbs__E71622130CA3366F");

                    b.HasIndex("CbsKey");

                    b.HasIndex("ProjectKey");

                    b.ToTable("site_cbs", (string)null);
                });

            modelBuilder.Entity("DBConnect.SiteInfo", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("site_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("site_name");

                    b.HasKey("SiteId")
                        .HasName("PK__site_inf__B22FDBCA9E6A154C");

                    b.ToTable("site_info", (string)null);
                });

            modelBuilder.Entity("DBConnect.SiteOrg", b =>
                {
                    b.Property<int>("SiteOrgsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("site_orgs_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteOrgsId"));

                    b.Property<int>("OrgKey")
                        .HasColumnType("int")
                        .HasColumnName("org_key");

                    b.Property<int>("SiteKey")
                        .HasColumnType("int")
                        .HasColumnName("site_key");

                    b.HasKey("SiteOrgsId")
                        .HasName("PK__site_org__76C35F2D06939FB7");

                    b.HasIndex("OrgKey");

                    b.HasIndex("SiteKey");

                    b.ToTable("site_orgs", (string)null);
                });

            modelBuilder.Entity("DBConnect.SitePackage", b =>
                {
                    b.Property<int>("SitePackagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("site_packages_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SitePackagesId"));

                    b.Property<int>("PackageKey")
                        .HasColumnType("int")
                        .HasColumnName("package_key");

                    b.Property<int>("SiteKey")
                        .HasColumnType("int")
                        .HasColumnName("site_key");

                    b.HasKey("SitePackagesId")
                        .HasName("PK__site_pac__9C9A65CAB4FBF30F");

                    b.HasIndex("PackageKey");

                    b.HasIndex("SiteKey");

                    b.ToTable("site_packages", (string)null);
                });

            modelBuilder.Entity("DBConnect.SiteTrade", b =>
                {
                    b.Property<int>("SiteTradesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("site_trades_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteTradesId"));

                    b.Property<int>("ProjectKey")
                        .HasColumnType("int")
                        .HasColumnName("project_key");

                    b.Property<int>("TradeKey")
                        .HasColumnType("int")
                        .HasColumnName("trade_key");

                    b.HasKey("SiteTradesId")
                        .HasName("PK__site_tra__7094B1E5F8EE658F");

                    b.HasIndex("ProjectKey");

                    b.HasIndex("TradeKey");

                    b.ToTable("site_trades", (string)null);
                });

            modelBuilder.Entity("DBConnect.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("StaffId")
                        .HasName("PK__staff__1963DD9C430315CB");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("DBConnect.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<string>("TradeDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trade_description");

                    b.HasKey("TradeId")
                        .HasName("PK__trades__AAFF5BF7117EF3FF");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("DBConnect.WeatherDatum", b =>
                {
                    b.Property<int>("WeatherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("weather_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time");

                    b.Property<Point>("Latitude")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("latitude");

                    b.Property<Point>("Longitude")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("longitude");

                    b.Property<int>("Temperature")
                        .HasColumnType("int")
                        .HasColumnName("temperature");

                    b.Property<string>("WeatherConditions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("weather_conditions");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("int")
                        .HasColumnName("wind_speed");

                    b.HasKey("WeatherId")
                        .HasName("PK__weather___4CDA2101E16CD1F6");

                    b.ToTable("weather_data", (string)null);
                });

            modelBuilder.Entity("DBConnect.DiaryEntry", b =>
                {
                    b.HasOne("DBConnect.LogType", "LogType")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("LogTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__diary_ent__log_t__5EBF139D");

                    b.HasOne("DBConnect.Org", "Organisation")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("OrganisationId")
                        .IsRequired()
                        .HasConstraintName("FK__diary_ent__organ__5FB337D6");

                    b.HasOne("DBConnect.ProjectInformation", "Project")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK__diary_ent__proje__5CD6CB2B");

                    b.HasOne("DBConnect.Staff", "Staff")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__diary_ent__staff__5DCAEF64");

                    b.HasOne("DBConnect.WeatherDatum", "Weather")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("WeatherId")
                        .HasConstraintName("FK__diary_ent__weath__60A75C0F");

                    b.Navigation("LogType");

                    b.Navigation("Organisation");

                    b.Navigation("Project");

                    b.Navigation("Staff");

                    b.Navigation("Weather");
                });

            modelBuilder.Entity("DBConnect.Downtime", b =>
                {
                    b.HasOne("DBConnect.Attachment", "AttachmentKeyNavigation")
                        .WithMany("Downtimes")
                        .HasForeignKey("AttachmentKey")
                        .HasConstraintName("FK__downtime__attach__3B75D760");

                    b.Navigation("AttachmentKeyNavigation");
                });

            modelBuilder.Entity("DBConnect.SiteCb", b =>
                {
                    b.HasOne("DBConnect.CoinsWb", "CbsKeyNavigation")
                        .WithMany("SiteCbs")
                        .HasForeignKey("CbsKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_cbs__cbs_ke__4D94879B");

                    b.HasOne("DBConnect.ProjectInformation", "ProjectKeyNavigation")
                        .WithMany("SiteCbs")
                        .HasForeignKey("ProjectKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_cbs__projec__4E88ABD4");

                    b.Navigation("CbsKeyNavigation");

                    b.Navigation("ProjectKeyNavigation");
                });

            modelBuilder.Entity("DBConnect.SiteOrg", b =>
                {
                    b.HasOne("DBConnect.Org", "OrgKeyNavigation")
                        .WithMany("SiteOrgs")
                        .HasForeignKey("OrgKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_orgs__org_k__5535A963");

                    b.HasOne("DBConnect.SiteInfo", "SiteKeyNavigation")
                        .WithMany("SiteOrgs")
                        .HasForeignKey("SiteKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_orgs__site___5629CD9C");

                    b.Navigation("OrgKeyNavigation");

                    b.Navigation("SiteKeyNavigation");
                });

            modelBuilder.Entity("DBConnect.SitePackage", b =>
                {
                    b.HasOne("DBConnect.PackageInformation", "PackageKeyNavigation")
                        .WithMany("SitePackages")
                        .HasForeignKey("PackageKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_pack__packa__59063A47");

                    b.HasOne("DBConnect.SiteInfo", "SiteKeyNavigation")
                        .WithMany("SitePackages")
                        .HasForeignKey("SiteKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_pack__site___59FA5E80");

                    b.Navigation("PackageKeyNavigation");

                    b.Navigation("SiteKeyNavigation");
                });

            modelBuilder.Entity("DBConnect.SiteTrade", b =>
                {
                    b.HasOne("DBConnect.ProjectInformation", "ProjectKeyNavigation")
                        .WithMany("SiteTrades")
                        .HasForeignKey("ProjectKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_trad__proje__52593CB8");

                    b.HasOne("DBConnect.Trade", "TradeKeyNavigation")
                        .WithMany("SiteTrades")
                        .HasForeignKey("TradeKey")
                        .IsRequired()
                        .HasConstraintName("FK__site_trad__trade__5165187F");

                    b.Navigation("ProjectKeyNavigation");

                    b.Navigation("TradeKeyNavigation");
                });

            modelBuilder.Entity("DBConnect.Attachment", b =>
                {
                    b.Navigation("Downtimes");
                });

            modelBuilder.Entity("DBConnect.CoinsWb", b =>
                {
                    b.Navigation("SiteCbs");
                });

            modelBuilder.Entity("DBConnect.LogType", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("DBConnect.Org", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("SiteOrgs");
                });

            modelBuilder.Entity("DBConnect.PackageInformation", b =>
                {
                    b.Navigation("SitePackages");
                });

            modelBuilder.Entity("DBConnect.ProjectInformation", b =>
                {
                    b.Navigation("DiaryEntries");

                    b.Navigation("SiteCbs");

                    b.Navigation("SiteTrades");
                });

            modelBuilder.Entity("DBConnect.SiteInfo", b =>
                {
                    b.Navigation("SiteOrgs");

                    b.Navigation("SitePackages");
                });

            modelBuilder.Entity("DBConnect.Staff", b =>
                {
                    b.Navigation("DiaryEntries");
                });

            modelBuilder.Entity("DBConnect.Trade", b =>
                {
                    b.Navigation("SiteTrades");
                });

            modelBuilder.Entity("DBConnect.WeatherDatum", b =>
                {
                    b.Navigation("DiaryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
